### ISSUE TITLE
Mouse offset on drag

### ISSUE THREAD

**Issue by delamitry** [httpete-ire/revealer#6]
When you drag the 'slider', it doesn't keep the mouse offset from where it was pressed.  The cursor jumps to the middle of the 'slider'. I don't know if I would call it a bug, maybe an oversight or could even be intended behavior I guess.

**Comment by httpete-ire** [comment]
good spot, thats not the intended behaviour so I'll go and fix that. Also the handler is way to big in the demo so the problem is  exaggerated
